title: "NDE documentation"

company_name: Evident Scientific

email: nde_support@evidentscientific.com

theme: just-the-docs

# Aux links for the upper right navigation
aux_links:
  "nde doc on GitHub":
    - "//github.com/just-the-docs/just-the-docs"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"